language: ruby
rvm:
  - "1.9.3"

# http://docs.travis-ci.com/user/languages/android/
env:
  matrix:
  #- ANDROID_SDKS=android-16,sys-img-armeabi-v7a-android-16 ANDROID_TARGET=android-16  ANDROID_ABI=armeabi-v7a
  #- ANDROID_SDKS=android-17,sys-img-armeabi-v7a-android-17 ANDROID_TARGET=android-17  ANDROID_ABI=armeabi-v7a
  - ANDROID_SDKS=android-19,sys-img-armeabi-v7a-android-19 ANDROID_TARGET=android-19  ANDROID_ABI=armeabi-v7a

before_install:
  # check the travis file
  - gem install travis-lint
  - travis-lint
  # Install base Android SDK
  - sudo apt-get update -qq
  - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq -o Dpkg::Options::="--force-confold" --force-yes --yes libgd2-xpm ia32-libs ia32-libs-multiarch > /dev/null ; fi
  # http://developer.android.com/sdk/index.html
  # http://dl.google.com/android/android-sdk_r23.0.2-linux.tgz
  - wget http://dl.google.com/android/android-sdk_r23.0.2-linux.tgz
  - tar xzf android-sdk_r23.0.2-linux.tgz
  - export ANDROID_HOME=$PWD/android-sdk-linux
  - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools   
  # Install required components.
  # For a full list, run `android list sdk -a --extended`
  # Note that sysimg-16 downloads the ARM, x86 and MIPS images (we should optimize this).
  # Other relevant API's:
  #  addon-google_apis-google-16
  #- android list sdk --no-ui --all --extended | grep -E '^id:' | awk -F '"' '{$1=""; print $2}'
  #- android list target
  - echo "y" | android update sdk --filter platform-tools,tools --no-ui --force
  - echo "y" | android update sdk --filter build-tools-20.0.0 --no-ui --force
  - echo "y" | android update sdk --filter extra-android-support --no-ui --force
  - echo "y" | android update sdk --filter $ANDROID_SDKS --no-ui --force


  # Create and start emulator 
  - echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  #- echo no | android create avd --force -n test -t $ANDROID_TARGET --abi $ANDROID_ABI
  #- echo no | android create avd --force -n test -t android-19 --abi armeabi-v7a
  #- echo no | android create avd --force -n test -t android-19 --abi x86
  - mksdcard 50M /tmp/sdcard.img
  - emulator -avd test -no-skin -no-audio -no-window -prop persist.sys.language=en -prop persist.sys.country=US -sdcard /tmp/sdcard.img & 

# Emulator Management: Create, Start and Wait
before_script:
  - adb wait-for-device
  - ./wait_for_emulator 
  - adb shell input keyevent 82 &

# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spe