#!/bin/bash

devices = "2"
failcounter=0
until [[ "$devices" =~ "3" ]]; do
  devices = `adb devices | wc -l`
  echo "$devices"
  let "failcounter += 1"
  if [[ $failcounter -gt 100 ]]; then
    echo "Failed to start emulator"
    exit 1
  fi
  sleep 10
done

bootanim=""
failcounter=0
until [[ "$bootanim" =~ "stopped" ]]; do
   bootanim=`adb -e shell getprop init.svc.bootanim 2>&1`
   echo "$bootanim"
   if [[ "$bootanim" =~ "not found" ]]; then
      let "failcounter += 1"
      if [[ $failcounter -gt 3 ]]; then
        echo "Failed to start emulator"
        exit 1
      fi
   fi
   sleep 1
done
echo "Done"
